export { default as Footer} from './footer/Footer'
export { default as Header} from './header/Header'
export { default as Characters} from './characters/Characters'
export { default as DetailedCharacters} from './detailed_characters/DetailedCharacters'
export { default as Seasons} from './seasons/Seasons'